saskatoon/member/urls.py
from django.urls import path, re_path
from . import views, autocomplete

urlpatterns = [

    # CREATE VIEWS
    path('person/create/',
         views.PersonCreateView.as_view(),
         name='person-create'),

    path('beneficiary/create/',
         views.OrganizationCreateView.as_view(),
         name='beneficiary-create'),

    # UPDATE VIEWS
    path('person/update/<int:pk>/',
         views.PersonUpdateView.as_view(),
         name='person-update'),

    path('beneficiary/update/<int:pk>/',
         views.OrganizationUpdateView.as_view(),
         name='beneficiary-update'),


    # AUTO-COMPLETE VIEWS
    re_path(r'^actor-autocomplete/$',
            autocomplete.ActorAutocomplete.as_view(),
            name='actor-autocomplete'),

    re_path(r'^person-autocomplete/$',
            autocomplete.PersonAutocomplete.as_view(),
            name='person-autocomplete'),

    re_path(r'^pickleader-autocomplete/$',
            autocomplete.PickLeaderAutocomplete.as_view(),
            name='pickleader-autocomplete'),

    re_path(r'^owner-autocomplete/$',
            autocomplete.OwnerAutocomplete.as_view(),
            name='owner-autocomplete'),

    re_path(r'^contact-autocomplete/$',
            autocomplete.ContactAutocomplete.as_view(),
            name='contact-autocomplete'),
]

saskatoon/saskatoon/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings

urlpatterns = [
    path('', include('sitebase.urls')),
    path('', include('member.urls')),
    path('', include('harvest.urls')),
    path('',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('rosetta/', include('rosetta.urls'))
]

handler400 = 'sitebase.views.handler400'
handler403 = 'sitebase.views.handler403'
handler404 = 'sitebase.views.handler404'
handler500 = 'sitebase.views.handler500'

saskatoon/sitebase/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, re_path
from sitebase import views

urlpatterns = [

    url(r'^$', views.Index.as_view(), name='home'),
    re_path(r'^calendar/$', views.Calendar.as_view(), name='calendar'),
    url(r'^jsoncal', views.JsonCalendar.as_view(), name='calendarJSON'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(),
         name ='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(),
         name ='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(),
         name ='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name ='password_reset_complete'),

]

saskatoon/member/forms.py
# coding: utf-8
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext_lazy as _
from django import forms
from dal import autocomplete
from harvest.models import Property
from member.models import AuthUser, Person, Organization, AUTH_GROUPS, STAFF_GROUPS


def validate_email(email):
    ''' check if a user with same email address is already registered'''
    if AuthUser.objects.filter(email=email).exists():
        raise forms.ValidationError(
            _("ERROR: email address < {} > is already registered!").format(email)
        )
    return email


class PersonCreateForm(forms.ModelForm):

    class Meta:
        model = Person
        exclude = ['redmine_contact_id', 'longitude', 'latitude']

    email = forms.EmailField(
        label=_("Email"),
        required=True
    )

    # when registering owner based off pending property info
    pending_property_id = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=False
    )

    roles = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=AUTH_GROUPS,
        required=True
    )

    field_order = ['roles', 'first_name', 'family_name', 'email', 'language']

    def clean(self):
        cleaned_data = super().clean()
        validate_email(cleaned_data['email'])

    def save(self):
        # create Person instance
        instance = super(PersonCreateForm, self).save()

        # create associated auth.user
        auth_user = AuthUser.objects.create(
                email=self.cleaned_data['email'],
                person=instance
        )
        roles = self.cleaned_data['roles']
        auth_user.set_roles(roles)

        # associate pending_property (if any)
        pid = self.cleaned_data['pending_property_id']
        if pid and 'owner' in roles:
            try:
                pending_property = Property.objects.get(id=pid)
                pending_property.owner = instance
                pending_property.save()
            except Exception as e: print(e)

        return instance


class PersonUpdateForm(forms.ModelForm):

    class Meta:
        model = Person
        exclude = ['redmine_contact_id', 'longitude', 'latitude']

    roles = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=AUTH_GROUPS,
        required=True
    )

    email = forms.EmailField(
        label=_("Email"),
        required=True
    )

    field_order = ['roles', 'email', 'first_name', 'family_name', 'language']

    def __init__(self, *args, **kwargs):
        request_user = kwargs.pop('request_user')
        super(PersonUpdateForm, self).__init__(*args, **kwargs)

        if not request_user.has_perm('member.change_authuser'):
            self.fields.pop('email')
            self.fields.pop('roles')
        else:
            try:
                auth_user = AuthUser.objects.get(person=self.instance)
                self.initial['roles'] = [g for g in auth_user.groups.all()]
                self.initial['email'] = auth_user.email
                roles = [g for g in auth_user.groups.all()]
            except ObjectDoesNotExist:
                self.fields.pop('email')
                self.fields.pop('roles')
                print("WARNING!: Person {} has no associated Auth.User!".format(self.instance))


    def clean(self):
        cleaned_data = super().clean()
        try:
            validate_email(cleaned_data['email'])
        except KeyError:
            pass

    def save(self):
        super(PersonUpdateForm, self).save()
        try:
            auth_user = AuthUser.objects.get(person=self.instance)
            auth_user.email = self.cleaned_data['email']
            auth_user.set_roles(self.cleaned_data['roles'])  # calls auth_user.save()
        except KeyError:
            pass
        return self.instance


class OrganizationForm(forms.ModelForm):

    class Meta:
        model = Organization
        exclude = ['redmine_contact_id', 'longitude', 'latitude']
        labels = {
            'is_beneficiary': _("Beneficiary organization"),
            'contact_person_role': _("Contact Position/Role"),
        }

        widgets = {
            'contact_person': autocomplete.ModelSelect2('contact-autocomplete'),
        }


class OrganizationCreateForm(OrganizationForm):

    contact_person = forms.ModelChoiceField(
        queryset=Person.objects.all(),
        label=_("Select Person"),
        widget=autocomplete.ModelSelect2('contact-autocomplete'),
        required=False,
    )

    create_new_person = forms.BooleanField(
        label=_("&nbsp;Register new contact person"),
        required=False
    )

    contact_first_name = forms.CharField(
        label=_("First Name"),
        help_text=_("This field is required"),
        required=False
    )

    contact_last_name = forms.CharField(
        label=_("Last Name"),
        required=False
    )

    contact_email = forms.EmailField(
        label=_("Email"),
        help_text=_("This field is required"),
        required=False
    )

    contact_phone = forms.CharField(
        label=_("Phone"),
        required=False
    )

    def clean(self):
        data = super().clean()
        person = data['contact_person']
        if not person:
            if data['contact_email'] and data['contact_first_name']:
                validate_email(data['contact_email'])
            else:
                raise forms.ValidationError(
                    _("ERROR: You must either select a Contact \
                    Person or create a new one and provide their personal information"))
        return data


    def save(self):
        # # create Organization instance
        instance = super(OrganizationCreateForm, self).save()

        # # create Contact Person/AuthUser
        person = Person.objects.create(
            first_name=self.cleaned_data['contact_first_name'],
            family_name=self.cleaned_data['contact_last_name'],
            phone=self.cleaned_data['contact_phone'])
        person.save()

        auth_user = AuthUser.objects.create(
            email=self.cleaned_data['contact_email'],
            person=person)
        auth_user.set_roles(['contact'])

        # # associate Contact to Organization
        instance.contact_person = person
        instance.save()

        return instance

saskatoon/sitebase/views.py
import datetime
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView
from harvest.models import Harvest, Property, RequestForParticipation
from harvest.forms import RequestForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

class Index(TemplateView):
    template_name = 'app/index.html'

#@method_decorator(login_required, name='dispatch')
class Calendar(TemplateView):
    template_name = 'app/calendar/view.html'

    def dispatch(self, request, *args, **kwargs):
        return super(Calendar, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Calendar, self).get_context_data(**kwargs)
        context['view'] = "calendar"
        # context['form_request'] = RequestForm()
        return context
class JsonCalendar(View):

    def get(self, request, *args, **kwargs):
        start_date = request.GET.get('start')
        end_date = request.GET.get('end')
        harvests = Harvest.objects.filter(end_date__lte=end_date, start_date__gte=start_date)
        events = []
        for harvest in harvests:
            if ( harvest.start_date and harvest.end_date and
                    (self.request.user.is_staff or harvest.is_publishable()) ):
                # https://fullcalendar.io/docs/event-object
                event = dict()
                event['url'] = '/participation/create?hid='+str(harvest.id)
                colors = ({'Date-scheduled': "#FFE180",
                           'Ready': "#BADDFF",
                           'Succeeded': "#9CF0DB",
                           'Cancelled': "#ED6D62"})
                event['display'] = "block"
                event['backgroundColor'] = colors.get(harvest.status, "#ededed")
                event['borderColor'] = event['backgroundColor']
                event['textColor'] = "#2A3F54"

                trees = [t.fruit_name for t in harvest.trees.all()]
                event['title'] = ", ".join(trees)
                if harvest.property.neighborhood.name != "Other":
                    event['title'] += " @ "+harvest.property.neighborhood.name

                # http://fullcalendar.io/docs/timezone/timezone/
                event['allday'] = "false"
                if harvest.start_date:
                    event['start'] = harvest.get_local_start()
                if harvest.end_date:
                    event['end'] = harvest.get_local_end()

                # additional info passed to 'extendedProps'
                requests_count = RequestForParticipation.objects.filter(harvest=harvest).count()

                event['extendedProps'] = {
                    'start_date': event['start'].strftime("%a. %b. %-d, %Y"),
                    #TODO handle scenario when end_date > start_date
                    'start_time': event['start'].strftime("%-I:%M %p"),
                    'end_time': event['end'].strftime("%-I:%M %p"),
                    'harvest_id': harvest.id,
                    'description': harvest.about,
                    'status': harvest.status,
                    'nb_required_pickers': harvest.nb_required_pickers,
                    'nb_requests': requests_count,
                    'trees': trees,
                    'total_harvested': harvest.get_total_distribution()
               }

                events.append(event)
                del event

        return JsonResponse(events, safe=False)


def handler400(request, exception):
    return render(request,'app/errors/400.html')

def handler403(request, exception):
    return render(request,'app/errors/403.html')

def handler404(request, exception):
    return render(request,'app/errors/404.html')

def handler500(request):
    return render(request,'app/errors/500.html')

def handler403_csrf_failue(request, reason=""):
    return render(request,'app/errors/403_csrf.html')

saskatoon/sitebase/templates/app/forms/base.html
{% extends 'app/base/view.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

{{ form.media }}

{% if form.non_field_errors %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="text-center alert alert-warning" role="alert">
                {{ form.non_field_errors }}
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="form-example-area">
    <div class="container">
        <div class="row">
                <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-xs-12">
                    <div class="form-example-wrap">
                        <div class="cmp-tb-hd">
                            <h2>{{ title }}</h2>
                        </div>
                        <div class="form-example-int">
                            <div class="form-group">

                                {% block form %}
                                <!-- {{ form }} -->
                                {% endblock form %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
     </div>
</div>

{% endblock content %}

saskatoon/sitebase/templates/app/forms/model_form.html
{% extends 'app/forms/base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block form %}

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">
            {% trans 'Save' %}
        </button>
        {% if cancel_url %}
        <button type="button" class="btn btn-default" style="margin-left:1rem;">
            <a href="{{ cancel_url }}">{% translate 'Cancel' %}</a>
        {% endif %}
        </button>
    </form>

{% endblock form %}

saskatoon/sitebase/templates/app/forms/organization_create_form.html
{% extends 'app/forms/base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block form %}
    <form method="post">
        {% csrf_token %}

        {{ form.is_beneficiary|as_crispy_field }}
        {{ form.civil_name|as_crispy_field }}
        {{ form.description|as_crispy_field }}

        {{ form.phone|as_crispy_field }}
        {{ form.street_number|as_crispy_field }}
        {{ form.street|as_crispy_field }}
        {{ form.complement|as_crispy_field }}
        {{ form.postal_code|as_crispy_field }}
        {{ form.neighborhood|as_crispy_field }}
        {{ form.city|as_crispy_field }}
        {{ form.state|as_crispy_field }}
        {{ form.country|as_crispy_field }}

        <br><hr>
        <h5>{% trans "Contact Person" %}</h5>

        {{ form.create_new_person|as_crispy_field }}

        <div id="existing-contact">
            {{ form.contact_person|as_crispy_field }}
        </div>

        <div class="collapse" id="new-contact">
            {{ form.contact_first_name|as_crispy_field }}
            {{ form.contact_last_name|as_crispy_field }}
            {{ form.contact_email|as_crispy_field }}
            {{ form.contact_phone|as_crispy_field }}
        </div>

        {{ form.contact_person_role|as_crispy_field }}

        <br>
        <button type="submit" class="btn btn-primary">
            {% trans 'Save' %}
        </button>
        {% if cancel_url %}
        <button type="button" class="btn btn-default" style="margin-left:1rem;">
            <a href="{{ cancel_url }}">{% translate 'Cancel' %}</a>
            {% endif %}
        </button>
    </form>


    <script>
        function collapseContactPerson(){
            if ($('#id_create_new_person').is(":checked")) {
                $('#existing-contact').hide();
                $('#new-contact').collapse('show');
            } else {
                $('#existing-contact').show();
                $('#new-contact').collapse('hide');
            }
        }

        $(function() {
            collapseContactPerson();

            $('#id_create_new_person').change(function() {
                collapseContactPerson();
            });

        });
    </script>

{% endblock form %}

saskatoon/sitebase/templates/app/forms/property_create_form.html
{% extends 'app/forms/base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block form %}

    <form method="post">
        {% csrf_token %}
        <br>
        <h5>{% trans "Status" %}</h5>
        {{ form.is_active|as_crispy_field }}
        {{ form.authorized|as_crispy_field }}

        <br><hr>
        <h5>{% trans "Trees" %}</h5>
        {{ form.trees|as_crispy_field }}
        {{ form.trees_location|as_crispy_field }}
        {{ form.avg_nb_required_pickers|as_crispy_field }}
        {{ form.trees_accessibility|as_crispy_field }}
        {{ form.public_access|as_crispy_field }}
        {{ form.neighbor_access|as_crispy_field }}
        {{ form.compost_bin|as_crispy_field }}
        {{ form.ladder_available|as_crispy_field }}
        {{ form.ladder_available_for_outside_picks|as_crispy_field }}
        {{ form.harvest_every_year|as_crispy_field }}
        {{ form.number_of_trees|as_crispy_field }}
        {{ form.approximative_maturity_date|as_crispy_field }}
        {{ form.fruits_height|as_crispy_field }}
        {{ form.additional_info|as_crispy_field }}

        <br><hr>
        <h5>{% trans "Owner" %}</h5>
        {{ form.create_new_owner|as_crispy_field }}

        <div id="existing-owner">
            {{ form.owner|as_crispy_field }}
        </div>

        <div class="collapse" id="new-owner">
            {{ form.owner_first_name|as_crispy_field }}
            {{ form.owner_last_name|as_crispy_field }}
            {{ form.owner_email|as_crispy_field }}
            {{ form.owner_phone|as_crispy_field }}
        </div>

        <br><hr>
        <h5>{% trans "Address" %}</h5>
            {{ form.street_number|as_crispy_field }}
            {{ form.street|as_crispy_field }}
            {{ form.complement|as_crispy_field }}
            {{ form.postal_code|as_crispy_field }}
            {{ form.neighborhood|as_crispy_field }}
            {{ form.city|as_crispy_field }}
            {{ form.state|as_crispy_field }}
            {{ form.country|as_crispy_field }}
            {{ form.publishable_location|as_crispy_field }}

        <br>
        <button type="submit" class="btn btn-primary">
            {% trans 'Save' %}
        </button>
        {% if cancel_url %}
        <button type="button" class="btn btn-default" style="margin-left:1rem;">
            <a href="{{ cancel_url }}">{% translate 'Cancel' %}</a>
            {% endif %}
        </button>
    </form>

    <script>

    function collapseOwner(){
        if ($('#id_create_new_owner').is(":checked")) {
            $('#existing-owner').hide();
            $('#new-owner').collapse('show');
        } else {
            $('#existing-owner').show();
            $('#new-owner').collapse('hide');
        }
    }

    $(function() {
        collapseOwner();

        $('#id_create_new_owner').change(function() {
            collapseOwner();
        });
    });

    </script>

{% endblock form %}

saskatoon/sitebase/templates/app/forms/property_create_public.html
{% extends 'app/base/view.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


{{ form.media }}

<div class="form-example-area">
    <div class="container">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-example-wrap">
                        <div class="cmp-tb-hd">
                            <h2>{% translate 'Add a new property' %}</h2>
                        </div>
                        <div class="form-example-int">
                            <div class="form-group">
                                  <form method="post">
                                      {% csrf_token %}
                                      {{ form|crispy }}
                                          <button type="submit" class="btn btn-primary">{% trans 'Send' %}</button>
                                  </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
     </div>
</div>

{% endblock content %}