saskatoon/harvest/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from harvest import api, views, autocomplete

# REST FRAMEWORK VIEWS
router = routers.DefaultRouter()
router.register('harvest', api.HarvestViewset, 'harvest')
router.register('property', api.PropertyViewset, 'property')
router.register('equipment', api.EquipmentViewset, 'equipment')
router.register('beneficiary', api.BeneficiaryViewset, 'beneficiary')
router.register('community', api.CommunityViewset, 'community')
router.register('participation', api.RequestForParticipationViewset, 'participation')

urlpatterns = [
    # CREATE VIEWS
    path(r'equipment/create/',
         views.EquipmentCreateView.as_view(),
         name='equipment-create'),

    path(r'property/create/',
         views.PropertyCreateView.as_view(),
         name='property-create'),

    path(r'property/create_public/',
         views.PropertyCreatePublicView.as_view(),
         name='property-create-public'),

    # backward compatibility with saskatoon-og
    path(r'harvest/properties/create_pending/',
         RedirectView.as_view(url='/property/create_public/')),

    path(r'harvest/create/',
         views.HarvestCreateView.as_view(),
         name='harvest-create'),

    path(r'participation/create/',
         views.RequestForParticipationCreateView.as_view(),
         name='rfp-create'),

    path(r'comment/create/',
         views.CommentCreateView.as_view(),
         name='comment-create'),

    path(r'yield/create/',
         views.harvest_yield_create,
         name='harvest-yield-create'),


    # DELETE VIEWS
    path(r'yield/delete/<int:id>/',
         views.harvest_yield_delete,
         name='harvest-yield-delete'),


    # UPDATE VIEWS
    re_path(r'^property/update/(?P<pk>\d+)/$',
            views.PropertyUpdateView.as_view(),
            name='property-update'),
    re_path(r'^participation/update/(?P<pk>\d+)/$',
            views.RequestForParticipationUpdateView.as_view(),
            name='participation-update'),
    re_path(r'^harvest/update/(?P<pk>\d+)/$',
            views.HarvestUpdateView.as_view(),
            name='harvest-update'),
    re_path(r'^equipment/update/(?P<pk>\d+)/$',
            views.EquipmentUpdateView.as_view(),
            name='equipment-update'),


    # AUTO-COMPLETE VIEWS
    re_path(r'^property-autocomplete/$',
            autocomplete.PropertyAutocomplete.as_view(),
            name='property-autocomplete'),

    re_path(r'^tree-autocomplete/$',
            autocomplete.TreeAutocomplete.as_view(),
            name='tree-autocomplete'),


    # MISC
    path(r'property/thanks/',
         views.TemplateView.as_view(template_name='app/property_thanks.html'),
         name='property-thanks'),

    path(r'stats/',
         views.TemplateView.as_view(template_name='app/stats.html'),
         name='statistics'),

]

urlpatterns += router.urls

saskatoon/member/urls.py
from django.urls import path, re_path
from . import views, autocomplete

urlpatterns = [

    # CREATE VIEWS
    path('person/create/',
         views.PersonCreateView.as_view(),
         name='person-create'),

    path('beneficiary/create/',
         views.OrganizationCreateView.as_view(),
         name='beneficiary-create'),

    # UPDATE VIEWS
    path('person/update/<int:pk>/',
         views.PersonUpdateView.as_view(),
         name='person-update'),

    path('beneficiary/update/<int:pk>/',
         views.OrganizationUpdateView.as_view(),
         name='beneficiary-update'),


    # AUTO-COMPLETE VIEWS
    re_path(r'^actor-autocomplete/$',
            autocomplete.ActorAutocomplete.as_view(),
            name='actor-autocomplete'),

    re_path(r'^person-autocomplete/$',
            autocomplete.PersonAutocomplete.as_view(),
            name='person-autocomplete'),

    re_path(r'^pickleader-autocomplete/$',
            autocomplete.PickLeaderAutocomplete.as_view(),
            name='pickleader-autocomplete'),

    re_path(r'^owner-autocomplete/$',
            autocomplete.OwnerAutocomplete.as_view(),
            name='owner-autocomplete'),

    re_path(r'^contact-autocomplete/$',
            autocomplete.ContactAutocomplete.as_view(),
            name='contact-autocomplete'),
]

saskatoon/saskatoon/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings

urlpatterns = [
    path('', include('sitebase.urls')),
    path('', include('member.urls')),
    path('', include('harvest.urls')),
    path('',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('rosetta/', include('rosetta.urls'))
]

handler400 = 'sitebase.views.handler400'
handler403 = 'sitebase.views.handler403'
handler404 = 'sitebase.views.handler404'
handler500 = 'sitebase.views.handler500'

saskatoon/sitebase/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, re_path
from sitebase import views

urlpatterns = [

    url(r'^$', views.Index.as_view(), name='home'),
    re_path(r'^calendar/$', views.Calendar.as_view(), name='calendar'),
    url(r'^jsoncal', views.JsonCalendar.as_view(), name='calendarJSON'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(),
         name ='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(),
         name ='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(),
         name ='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name ='password_reset_complete'),

]

saskatoon/harvest/models.py
# coding: utf-8

from harvest import signals
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import datetime
from djgeojson.fields import PointField
from phone_field import PhoneField
from django.db.models.query_utils import Q


HARVESTS_STATUS_CHOICES = (
    (
        "To-be-confirmed",
        _("To be confirmed"),
    ),
    (
        "Orphan",
        _("Orphan"),
    ),
    (
        "Adopted",
        _("Adopted"),
    ),
    (
        "Date-scheduled",
        _("Date scheduled"),
    ),
    (
        "Ready",
        _("Ready"),
    ),
    (
        "Succeeded",
        _("Succeeded"),
    ),
    (
        "Cancelled",
        _("Cancelled"),
    )
)


class TreeType(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=20,
        default=''
    )

    image = models.ImageField(
        upload_to='fruits_images',
        verbose_name=_("Fruit image"),
        null=True
    )

    fruit_name = models.CharField(
        verbose_name=_("Fruit name"),
        max_length=20
    )

    season_start = models.DateField(
        verbose_name=_("Season start date"),
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = _("tree type")
        verbose_name_plural = _("tree types")
        ordering = ["name"]

    def __str__(self):
        return self.name


class EquipmentType(models.Model):
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=50
    )

    class Meta:
        verbose_name = _("equipment type")
        verbose_name_plural = _("equipment types")

    def __str__(self):
        return self.name


class Property(models.Model):
    """
    Property where you find one or more trees for harvesting.
    """
    is_active = models.BooleanField(
        verbose_name=_("Is active"),
        help_text=_("This property exists and may be able to host a pick"),
        default=True
    )

    authorized = models.BooleanField(
        verbose_name=_("Authorized for this season"),
        help_text=_("Harvest in this property has been authorized for the current season by its owner"),
        null=True,
        default=None
    )

    pending = models.BooleanField(
        verbose_name=_("Pending"),
        help_text=_("This property was created through a public form and needs to be validated by an administrator"),
        default=True
    )

    pending_contact_first_name = models.CharField(
        blank=True,
        verbose_name=_("Contact first name"),
        help_text=_("First name of the person to be contacted for confirmation"),
        max_length=50
    )

    pending_contact_family_name = models.CharField(
        blank=True,
        verbose_name=_("Contact family name"),
        help_text=_("Family name of the person to be contacted for confirmation"),
        max_length=50
    )

    pending_contact_phone = PhoneField(
        blank=True,
        verbose_name=_("Contact phone number"),
        help_text=_("Phone number to be used for confirmation"),
    )

    pending_contact_email = models.EmailField(
        verbose_name=_("Contact email"),
        help_text=_("Email address to be used for confirmation"),
        null=True,
        blank=True,
    )

    pending_newsletter = models.BooleanField(
        verbose_name=_("Newsletter subscription"),
        default=False
    )

    pending_recurring = models.BooleanField(
        verbose_name=_("Recurring property signup"),
        default=False
    )

    geom = PointField(null=True, blank=True)

    owner = models.ForeignKey(
        'member.Actor',
        null=True,
        blank=True,
        verbose_name=_("Owner"),
        on_delete=models.CASCADE,
    )

    # FIXME: add help_text in forms.py
    trees = models.ManyToManyField(
        'TreeType',
        verbose_name=_("Fruit tree/vine type(s)"),
        help_text=_(
            'Select multiple fruit types if applicable. Unknown fruit type or colour can be mentioned in the additional comments at the bottom.'),
    )

    trees_location = models.CharField(
        verbose_name=_("Trees location"),
        help_text=_("Front yard or backyard?"),
        null=True,
        blank=True,
        max_length=200
    )

    trees_accessibility = models.CharField(
        verbose_name=_("Trees accessibility"),
        help_text=_("Any info on how to access the tree (eg. key, gate etc)"),
        null=True,
        blank=True,
        max_length=200
    )

    avg_nb_required_pickers = models.PositiveIntegerField(
        verbose_name=_("Required pickers on average"),
        null=True,
        default=1
    )

    public_access = models.BooleanField(
        verbose_name=_("Publicly accessible"),
        default=False,
    )

    neighbor_access = models.BooleanField(
        verbose_name=_("Access to neighboring terrain if needed"),
        default=False,
    )

    compost_bin = models.BooleanField(
        verbose_name=_("Compost bin closeby"),
        default=False,
    )

    ladder_available = models.BooleanField(
        verbose_name=_("There is a ladder available in the property"),
        default=False,
    )

    ladder_available_for_outside_picks = models.BooleanField(
        verbose_name=_("A ladder is available in the property and can be used for nearby picks"),
        default=False,
    )

    harvest_every_year = models.BooleanField(
        verbose_name=_("Produces fruits every year"),
        default=False,
    )

    number_of_trees = models.PositiveIntegerField(
        verbose_name=_("Total number of trees/vines on this property"),
        blank=True,
        null=True
    )

    approximative_maturity_date = models.DateField(
        verbose_name=_("Approximative maturity date"),
        help_text=_("When is the tree commonly ready to be harvested?"),
        blank=True,
        null=True
    )

    fruits_height = models.PositiveIntegerField(
        verbose_name=_("Height of lowest fruits (meters)"),
        blank=True,
        null=True
    )

    street_number = models.CharField(
        verbose_name=_("Number"),
        max_length=10,
        null=True,
        blank=True
    )

    street = models.CharField(
        verbose_name=_("Street"),
        max_length=50,
        null=True,
        blank=True
    )

    complement = models.CharField(
        verbose_name=_("Complement"),
        max_length=150,
        null=True,
        blank=True
    )

    postal_code = models.CharField(
        verbose_name=_("Postal code"),
        max_length=10,
        null=True,
        blank=True
    )

    publishable_location = models.CharField(
        verbose_name=_("Publishable location"),
        help_text=_("Aproximative location to be used in public communications (not the actual address)"),
        max_length=50,
        null=True,
        blank=True
    )

    neighborhood = models.ForeignKey(
        'member.Neighborhood',
        verbose_name=_("Neighborhood"),
        null=True,
        on_delete=models.CASCADE,
    )

    city = models.ForeignKey(
        'member.City',
        verbose_name=_("City"),
        null=True,
        default=1,
        on_delete=models.CASCADE,
    )

    state = models.ForeignKey(
        'member.State',
        verbose_name=_("Province"),
        null=True,
        default=1,
        on_delete=models.CASCADE,
    )

    country = models.ForeignKey(
        'member.Country',
        verbose_name=_("Country"),
        null=True,
        default=1,
        on_delete=models.CASCADE,
    )

    longitude = models.FloatField(
        verbose_name=_("Longitude"),
        null=True,
        blank=True
    )

    latitude = models.FloatField(
        verbose_name=_("Latitude"),
        null=True,
        blank=True
    )

    additional_info = models.CharField(
        verbose_name=_("Additional information"),
        help_text=_("Any additional information that we should be aware of"),
        max_length=1000,
        null=True,
        blank=True
    )

    changed_by = models.ForeignKey(
        'member.AuthUser',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = _("property")
        verbose_name_plural = _("properties")

    @property
    def short_address(self):
        if self.street_number and self.street and self.complement:
            return "%s %s, %s" % (
                self.street_number,
                self.street,
                self.complement
            )
        elif self.street and self.street_number:
            return "%s %s" % (
                self.street_number,
                self.street
            )
        elif self.street and self.complement:
            return "%s, %s" % (
                self.street,
                self.complement
            )
        else:
            return self.street

    @property
    def last_succeeded_harvest_date(self):
        """Returns the start_date of the last successful Harvest in this Property"""
        last_harvest = self.harvests.filter(status="Succeeded").order_by('start_date').last()
        return last_harvest.start_date if last_harvest else None

    def get_owner_subclass(self):
        if self.owner:
            if self.owner.is_person:
                return self.owner.person
            if self.owner.is_organization:
                return self.owner.organization
        return None

    @property
    def owner_email(self):
        owner_subclass = self.get_owner_subclass()
        return owner_subclass.email if owner_subclass else None

    @property
    def owner_phone(self):
        owner_subclass = self.get_owner_subclass()
        return owner_subclass.phone if owner_subclass else None

    @property
    def owner_name(self):
        if self.owner:
            return self.owner.__str__()
        return u"(%s %s)" % (self.pending_contact_first_name,

saskatoon/sitebase/templates/app/detail_views/property/about.html
{% load i18n %}
{% load static %}
{% load get_fruit_name_icon %}
<div class="search-engine-int">
    <div class="contact-hd search-hd-eg">
        <h2>{% translate 'About this property' %}</h2>
        <hr>
        <div class="tpgp-ele-tx">
            <h2>{% translate 'Address' %}</h2>
            <p>{{ property.address }}</p>
            <p>{{ property.neighborhood.name }}</p>
            <br>

            <h2>{% translate 'Available tree' %}(s)</h2>
            <ul>
                {% for tree in property.trees %}
                <li>- {{ tree.name }} {{ tree.fruit_name|get_fruit_name_icon }}</li>
                {% endfor %}
            </ul>
            <br>

           <h2>{% translate 'Accessibility' %}</h2>
           <ul>
            <li>- {{ property.trees_location|default:"" }}</li>
            <li>- {{ property.trees_accessibility|default:"" }}</li>
            <li>- {{ property.additional_info|default:"" }}</li>
           </ul>
        </div>
    </div>
</div>

saskatoon/sitebase/templates/app/detail_views/property/breadcomb.html
{% load i18n %}
{% load static %}
<div class="breadcomb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="breadcomb-list">
                    <div class="row">
                        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                            <div class="breadcomb-wp">
                                <div class="breadcomb-icon">
                                    <i class="notika-icon notika-windows"></i>
                                </div>
                                <div class="breadcomb-ctn">
                                    <h1>
                                    {% if property.owner %}
                                        {{ property.title }}
                                    {% elif property.pending_contact_first_name or property.pending_contact_family_name %}
                                        {{ property.pending_contact_first_name }} {{ property.pending_contact_family_name }}
                                        at {{ property.address }}
                                    {% else %}
                                        {{ property.address }}
                                    {% endif %}
                                    </h1>
                                    {% if property.pending %}
                                        <h4>** {% translate 'PENDING' %} **</h4>
                                    {% elif property.last_succeeded_harvest_date %}
                                        <p>{% trans "Last succeeded harvest"  %}
                                            on {{ property.last_succeeded_harvest_date|date }}
                                        </p>
                                    {% else %}
                                        <p>{% translate 'No succeeded harvest on this property so far' %}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                            <div class="breadcomb-report">
                                {% if perms.harvest.change_property %}
                                    <a href="/property/update/{{ property.id }}">
                                        <button title="Edit Property" class="btn">
                                            {% trans "Edit Property" %}</button>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

saskatoon/sitebase/templates/app/detail_views/property/contact.html
{% load i18n %}
{% load static %}
<div class="search-engine-int sm-res-mg-t-30 tb-res-mg-t-30 tb-res-ds-n dk-res-ds">

    <div class="contact-hd search-hd-eg">
        {% if property.owner %}
            <h2>{% trans "Owner" %}
            {% if property.owner_type.is_organization %}
                <small>{% trans "(Organization)" %}</small>
            {% elif property.owner_type.is_person and perms.member.change_person %}
                &nbsp;
                <small><a href="/person/update/{{property.owner.pk}}/?pid={{property.id}}">
                        <i class="fa fa-pencil"></i> {% trans "edit" %}
                </a></small>
            {% endif %}
            </h2>
        {% else %}
            <h2>{% trans "Unregistered owner" %}
            {% if perms.member.add_person %}
                &nbsp;
                <small><a href="/person/create/?pid={{property.id}}">
                        <i class="fa fa-pencil"></i> {% translate 'register' %}
                </a></small>
            {% endif %}
            </h2>
        {% endif %}
        </h2><hr>
    </div>

    <p class="lead">
    {% if property.owner %}
        {{ property.owner.name }}
    {% else %}
        {{ property.pending_contact_first_name }} {{ property.pending_contact_family_name }}
    {% endif %}
    </p>

    <table class="table">
        <tbody>
        {% if property.owner_type.is_organization %}
            <tr>
                <td>{% trans "Contact" %}</td>
                <td class="text-right">
                    <h5>{{ property.owner.contact }}</h5>
                </td>
            </tr>
        {% endif %}

        <tr>
            <td>{% trans "Phone" %}</td>
            <td class="text-right">
                <h5>
                {% if property.owner %}
                    {{ property.owner.phone }}
                {% else %}
                    {{ property.pending_contact_phone }}
                {% endif %}
                </h5>
            </td>
        </tr>

        <tr>
            <td>{% trans "Email" %}</td>
            <td class="text-right">
                <h5>
                {% if property.owner %}
                    {{ property.owner.email }}
                {% else %}
                    {{ property.pending_contact_email }}
                {% endif %}
                </h5>
            </td>
        </tr>

        {% if property.owner %}
            {% if property.owner.language %}
                <tr>
                    <td>{% trans "Language" %}</td>
                    <td class="text-right">
                        <h5>{{ property.owner.language }}</h5>
                    </td>
                </tr>
            {% endif %}
        {% else %}
            <!-- TODO: preferred language -->
        {% endif %}

        {% if property.owner.comments %}
        <tr>
            <td>{% trans "Comments" %}</td>
            <td class="text-right">
                <p>{{ property.owner.comments }}</p>
            </td>
        </tr>
        {% endif %}
    </table>

</div>

saskatoon/sitebase/templates/app/detail_views/property/features.html
{% load i18n %}
{% load static %}
<div class="search-engine-int sm-res-mg-t-30 tb-res-mg-t-30 tb-res-mg-t-0">

    <div class="contact-hd search-hd-eg">
        <h2>{% translate 'Property features' %}</h2>
    </div>

    <div class="search-eg-table">
        <table class="table">
            <tbody>
            {% if property.is_active %}

                {% if property.pending %}
                    <tr> <td class="text-right">
                            <b class="text-danger">
                                {% trans "Pending validation" %}
                            </b>
                            <i class="notika-icon notika-close"></i>
                    </td></tr>

                    {% if property.pending_recurring %}
                        <tr><td class="text-right">
                            <b>
                                {% trans "Has already been registered in the past" %}
                            </b>
                            <i class="notika-icon notika-checked"></i>
                        </td></tr>
                    {% else %}
                        <tr><td class="text-right">
                            {% trans "Has never been registered before" %}
                            <i class="notika-icon notika-checked"></i>
                        </td></tr>
                    {% endif %}

                {% else %}
                    <tr><td class="text-right">
                        {% trans "Validated" %}
                        <i class="notika-icon notika-checked"></i>
                    </td></tr>
                {% endif %}


                {% if property.authorized is None %}
                    <tr><td class="text-right">
                        <b class="text-danger">
                            {% trans "Not yet authorized" %}
                        </b>
                        <i class="notika-icon notika-checked"></i>
                    </td></tr>
                {% elif property.authorized %}
                    <tr><td class="text-right">
                        {% trans "Authorized for the current season" %}
                        <i class="notika-icon notika-checked"></i>
                    </td></tr>
                {% else %}
                    <tr><td class="text-right">
                        <b class="text-danger">
                            {% trans "Not authorized for this season" %}
                        </b>
                        <i class="notika-icon notika-close"></i>
                    </td></tr>
                {% endif %}

            {% else %}
                <tr><td class="text-right">
                    <b class="text-danger">
                        {% trans "This property is marked as inactive" %}
                    </b>
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}

            {% if property.harvest_every_year %}
                <tr><td class="text-right">
                    {% trans "Produces fruits every year" %}
                    <i class="notika-icon notika-checked"></i>
                </td></tr>
            {% else %}
                <tr><td class="text-right">
                    {% trans "Does not produce fruits every year" %}
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}

            {% if property.avg_nb_required_pickers %}
                <tr><td class="text-right">
                    {{ property.avg_nb_required_pickers }}
                    {% trans "picker(s) needed" %}
                    <i class="notika-icon notika-checked"></i>
                </td></tr>
            {% else %}
                <tr><td class="text-right">
                    {% trans "Number of pickers not specified" %}
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}

            {% if property.ladder_available %}
                <tr><td class="text-right">
                    {% trans "Ladder available" %}
                    <i class="notika-icon notika-checked"></i>
                </td></tr>
                {% if property.ladder_available_for_outside_picks %}
                    <tr><td class="text-right">
                        {% trans "Ladder available for outside picks" %}
                        <i class="notika-icon notika-checked"></i>
                    </td></tr>
                {% endif %}
            {% else %}
                <tr><td class="text-right">
                    {% trans "No ladder available" %}
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}

            {% if property.public_access %}
                <tr><td class="text-right">
                    {% trans "Publicly accessible" %}
                    <i class="notika-icon notika-checked"></i>
                </td></tr>
            {% else %}
                <tr><td class="text-right">
                    {% trans "Not publicly accessible" %}
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}

            {% if property.neighbor_access %}
                <tr><td class="text-right">
                    {% trans "Access to neighbors terrain" %}
                    <i class="notika-icon notika-checked"></i>
                </td></tr>
            {% else %}
                <tr><td class="text-right">
                    {% trans "No permission to access neighbors terrain" %}
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}

            {% if property.compost_bin %}
                <tr><td class="text-right">
                    {% trans "Compost bin closeby" %}
                    <i class="notika-icon notika-checked"></i>
                </td></tr>
            {% else %}
                <tr><td class="text-right">
                    {% trans "No compost bin closeby" %}
                    <i class="notika-icon notika-close"></i>
                </td></tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

saskatoon/sitebase/templates/app/detail_views/property/harvest_table.html
{% load i18n %}
{% load static %}
<div class="search-engine-area mg-t-30">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="data-table-list">
                    <div class="table-responsive">
                        <h4> {% trans Harvests %}
                            {% if perms.harvest.add_harvest %}
                                &nbsp;
                                <a href="/harvest/create/?pid={{ property.id }}">
                                    <button title="New harvest"
                                            class="btn btn-success notika-btn-success waves-effect">
                                        <i class="fa fa-plus"></i>
                                        {% trans "New Harvest" %}
                                    </button>
                                    <!-- </div> -->
                                </a>
                            {% endif %}
                        </h4>
                        <table class="table table-striped" id="data-table-basic">
                            <thead>
                            <tr>
                                <th style="width: 12%">{% trans "Pickleader" %}</th>
                                <th style="width: 12%">{% trans "Status" %}</th>
                                <th style="width: 20%">{% trans "Date" %}</th>
                            </tr>
                            </thead>
                            {% for harvest in property.harvests %}

                                {% include 'app/detail_views/property/harvest_row.html' %}

                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>