saskatoon/member/urls.py
from django.urls import path, re_path
from . import views, autocomplete

urlpatterns = [

    # CREATE VIEWS
    path('person/create/',
         views.PersonCreateView.as_view(),
         name='person-create'),

    path('beneficiary/create/',
         views.OrganizationCreateView.as_view(),
         name='beneficiary-create'),

    # UPDATE VIEWS
    path('person/update/<int:pk>/',
         views.PersonUpdateView.as_view(),
         name='person-update'),

    path('beneficiary/update/<int:pk>/',
         views.OrganizationUpdateView.as_view(),
         name='beneficiary-update'),


    # AUTO-COMPLETE VIEWS
    re_path(r'^actor-autocomplete/$',
            autocomplete.ActorAutocomplete.as_view(),
            name='actor-autocomplete'),

    re_path(r'^person-autocomplete/$',
            autocomplete.PersonAutocomplete.as_view(),
            name='person-autocomplete'),

    re_path(r'^pickleader-autocomplete/$',
            autocomplete.PickLeaderAutocomplete.as_view(),
            name='pickleader-autocomplete'),

    re_path(r'^owner-autocomplete/$',
            autocomplete.OwnerAutocomplete.as_view(),
            name='owner-autocomplete'),

    re_path(r'^contact-autocomplete/$',
            autocomplete.ContactAutocomplete.as_view(),
            name='contact-autocomplete'),
]

saskatoon/saskatoon/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings

urlpatterns = [
    path('', include('sitebase.urls')),
    path('', include('member.urls')),
    path('', include('harvest.urls')),
    path('',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('rosetta/', include('rosetta.urls'))
]

handler400 = 'sitebase.views.handler400'
handler403 = 'sitebase.views.handler403'
handler404 = 'sitebase.views.handler404'
handler500 = 'sitebase.views.handler500'

saskatoon/sitebase/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, re_path
from sitebase import views

urlpatterns = [

    url(r'^$', views.Index.as_view(), name='home'),
    re_path(r'^calendar/$', views.Calendar.as_view(), name='calendar'),
    url(r'^jsoncal', views.JsonCalendar.as_view(), name='calendarJSON'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(),
         name ='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(),
         name ='password_reset_done'),

    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(),
         name ='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name ='password_reset_complete'),

]

saskatoon/harvest/forms.py
# coding: utf-8
from ckeditor.widgets import CKEditorWidget
from dal import autocomplete
from datetime import datetime as dt
from django import forms
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from harvest.models import (RequestForParticipation, Harvest, HarvestYield, Comment,
                            Equipment, PropertyImage, HarvestImage, TreeType, Property)
from member.forms import validate_email
from member.models import AuthUser, Person, Organization
from postalcodes_ca import parse_postal_code

# Request for participation
class RequestForm(forms.ModelForm):
    picker_email = forms.EmailField(
        help_text=_("Enter a valid email address, please."),
        label=_("Email")
    )
    picker_first_name = forms.CharField(
        label=_("First name")
    )
    picker_family_name = forms.CharField(
        label=_("Family name")
    )
    picker_phone = forms.CharField(
        label=_("Phone")
    )
    comment = forms.CharField(
        label=_("Comment"),
        required=False,
        widget=forms.widgets.Textarea()
    )
    harvest_id = forms.CharField(
        widget=forms.HiddenInput()
    )
    notes_from_pickleader = forms.CharField(
        widget=forms.HiddenInput(),
        required=False
    )

    def clean(self):
        email = self.cleaned_data['picker_email']
        if AuthUser.objects.filter(email=email).exists():
            auth_user = AuthUser.objects.get(email=email) #email field is unique

            # check if email already requested for the same harvest
            if RequestForParticipation.objects.filter(picker=auth_user.person,
                    harvest_id=self.cleaned_data['harvest_id']).exists():
                raise forms.ValidationError(
                    _("You have already requested to join this pick.")
                )

    def send_email(self, subject, message, mail_to):
        send_mail(
                subject,
                message,
                'info@lesfruitsdefendus.org',
                mail_to,
                fail_silently=False,
            )

    def save(self):
        instance = super(RequestForm, self).save(commit=False)

        harvest_id = self.cleaned_data['harvest_id']
        first_name = self.cleaned_data['picker_first_name']
        family_name = self.cleaned_data['picker_family_name']
        phone = self.cleaned_data['picker_phone']
        email = self.cleaned_data['picker_email']
        comment = self.cleaned_data['comment']
        harvest_obj = Harvest.objects.get(id=harvest_id)

        # check if the email is already registered
        auth_user_count = AuthUser.objects.filter(email=email).count()
        instance.harvest = harvest_obj

        if auth_user_count > 0:  # user is already in the database
            auth_user = AuthUser.objects.get(email=email)
            instance.picker = auth_user.person
        else:
            # user is not in the database, so create a
            # new one and link it to Person obj

            instance.picker = Person.objects.create(
                first_name=first_name,
                family_name=family_name,
                phone=phone
            )
            auth_user = AuthUser.objects.create(
                email=email,
                person=instance.picker
            )

            group, __ = Group.objects.get_or_create(name='volunteer')
            auth_user.groups.add(group)

        # Building email content
        pick_leader_email = list()
        pick_leader_email.append(str(harvest_obj.pick_leader.email))
        pick_leader_name = harvest_obj.pick_leader.person.first_name
        publishable_location = harvest_obj.property.publishable_location
        mail_subject = _(u"New request from ") + \
            "%s %s" % (first_name, family_name)
        message = u"Hi %s, " \
                  u"\n\n" \
                  u"There is a new request from %s to participate " \
                  u"in harvest #%s at '%s'.\n\n" \
                  u"Full name: %s %s\n" \
                  u"Email: %s\n" \
                  u"Phone: %s\n" \
                  u"Comment: %s\n\n" \
                  u"Please contact %s directly and then manage " \
                  u"this request through\n" \
                  u"http://saskatoon.lesfruitsdefendus.org/harvest/%s\n\n" \
                  u"Yours,\n" \
                  u"--\n" \
                  u"Saskatoon Harvest System" % \
                  (
                      pick_leader_name,
                      first_name,
                      harvest_id,
                      publishable_location,
                      first_name,
                      family_name,
                      email,
                      phone,
                      comment,
                      first_name,
                      harvest_id
                  )

        # Sending email to pick leader
        # self.send_email(mail_subject, message, pick_leader_email)

        instance.save()

        return instance

    class Meta:
        model = RequestForParticipation
        fields = [
            'number_of_people',
            'picker_first_name',
            'picker_family_name',
            'picker_email',
            'picker_phone',
            'comment',
            'harvest_id',
            'notes_from_pickleader'
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]

        widgets = {
            'content': forms.Textarea(
                attrs={
                    'placeholder': _(u"Your comment here.")
                }
            ),
        }


# To be used by the pick leader to accept/deny/etc and add
# notes on a picker
class RFPManageForm(forms.ModelForm):
    STATUS_CHOICES = [
        (
            'pending',
            _("Pending")
        ),
        (
            'accepted',
            _('Accept this request')
        ),
        (
            'refused',
            _("Refuse this request")
        ),
        (
            'cancelled',
            _("Canceled by picker")
        )
    ]

    status = forms.ChoiceField(
        label=_('Participation request status'),
        choices=STATUS_CHOICES,
        widget=forms.RadioSelect(),
        required=True
    )

    class Meta:
        model = RequestForParticipation
        fields = ['status', 'notes_from_pickleader']

    def save(self):
        instance = super(RFPManageForm, self).save(commit=False)
        status = self.cleaned_data['status']
        instance.is_cancelled = (status == 'cancelled')
        instance.acceptation_date = dt.now() if status == 'accepted' else None
        instance.is_accepted = {'accepted': True, 'refused': False}.get(status, None)
        instance.save()
        return instance

# Used in admin interface
class RFPForm(forms.ModelForm):
    class Meta:
        model = RequestForParticipation
        fields = '__all__'


class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = PropertyImage
        fields = [
            'image'
        ]


class HarvestImageForm(forms.ModelForm):
    class Meta:
        model = HarvestImage
        fields = [
            'image'
        ]

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        exclude = ['longitude', 'latitude', 'geom', 'changed_by',
                   'pending_contact_first_name', 'pending_contact_family_name',
                   'pending_contact_phone', 'pending_contact_email',
                   'pending_recurring', 'pending_newsletter']

        widgets = {
            'owner': autocomplete.ModelSelect2('owner-autocomplete'),
            'trees': autocomplete.ModelSelect2Multiple('tree-autocomplete'),
            'additional_info': forms.Textarea(),
            'avg_nb_required_pickers': forms.NumberInput()
        }


    field_order = ['pending', 'is_active', 'authorized', 'owner']

    approximative_maturity_date = forms.DateField(
        input_formats=('%Y-%m-%d',),
        required=False,
        widget=forms.DateInput(
            format='%Y-%m-%d',
        )
    )

class PropertyCreateForm(PropertyForm):

    create_new_owner = forms.BooleanField(
        label=_("Register new owner"),
        required=False

    )
    owner_first_name = forms.CharField(
        label=_("First Name"),
        help_text=_("This field is required"),
        required=False
    )

    owner_last_name = forms.CharField(
        label=_("Last Name"),
        required=False
    )

    owner_phone = forms.CharField(
        label=_("Phone"),
        required=False
    )

    owner_email = forms.EmailField(
        label=_("Email"),
        help_text=_("This field is required"),
        required=False
    )


    def clean(self):
        data = super().clean()
        if not data['owner']:
            if data['owner_email'] and data['owner_first_name']:
                validate_email(data['owner_email'])
            else:
                raise forms.ValidationError(
                    _("ERROR: You must either select an Owner \
                    or create a new one and provide their personal information"))
        return data


    def save(self):
        # # create Property instance
        instance = super(PropertyCreateForm, self).save()

        # # create Owner Person/AuthUser
        person = Person.objects.create(
            first_name=self.cleaned_data['owner_first_name'],
            family_name=self.cleaned_data['owner_last_name'],
            phone=self.cleaned_data['owner_phone'])
        person.save()

        auth_user = AuthUser.objects.create(
            email=self.cleaned_data['owner_email'],
            person=person)
        auth_user.set_roles(['owner'])

        # # associate Owner to Property
        instance.owner = person
        instance.save()

        return instance

saskatoon/sitebase/views.py
import datetime
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView
from harvest.models import Harvest, Property, RequestForParticipation
from harvest.forms import RequestForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

class Index(TemplateView):
    template_name = 'app/index.html'

#@method_decorator(login_required, name='dispatch')
class Calendar(TemplateView):
    template_name = 'app/calendar/view.html'

    def dispatch(self, request, *args, **kwargs):
        return super(Calendar, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Calendar, self).get_context_data(**kwargs)
        context['view'] = "calendar"
        # context['form_request'] = RequestForm()
        return context
class JsonCalendar(View):

    def get(self, request, *args, **kwargs):
        start_date = request.GET.get('start')
        end_date = request.GET.get('end')
        harvests = Harvest.objects.filter(end_date__lte=end_date, start_date__gte=start_date)
        events = []
        for harvest in harvests:
            if ( harvest.start_date and harvest.end_date and
                    (self.request.user.is_staff or harvest.is_publishable()) ):
                # https://fullcalendar.io/docs/event-object
                event = dict()
                event['url'] = '/participation/create?hid='+str(harvest.id)
                colors = ({'Date-scheduled': "#FFE180",
                           'Ready': "#BADDFF",
                           'Succeeded': "#9CF0DB",
                           'Cancelled': "#ED6D62"})
                event['display'] = "block"
                event['backgroundColor'] = colors.get(harvest.status, "#ededed")
                event['borderColor'] = event['backgroundColor']
                event['textColor'] = "#2A3F54"

                trees = [t.fruit_name for t in harvest.trees.all()]
                event['title'] = ", ".join(trees)
                if harvest.property.neighborhood.name != "Other":
                    event['title'] += " @ "+harvest.property.neighborhood.name

                # http://fullcalendar.io/docs/timezone/timezone/
                event['allday'] = "false"
                if harvest.start_date:
                    event['start'] = harvest.get_local_start()
                if harvest.end_date:
                    event['end'] = harvest.get_local_end()

                # additional info passed to 'extendedProps'
                requests_count = RequestForParticipation.objects.filter(harvest=harvest).count()

                event['extendedProps'] = {
                    'start_date': event['start'].strftime("%a. %b. %-d, %Y"),
                    #TODO handle scenario when end_date > start_date
                    'start_time': event['start'].strftime("%-I:%M %p"),
                    'end_time': event['end'].strftime("%-I:%M %p"),
                    'harvest_id': harvest.id,
                    'description': harvest.about,
                    'status': harvest.status,
                    'nb_required_pickers': harvest.nb_required_pickers,
                    'nb_requests': requests_count,
                    'trees': trees,
                    'total_harvested': harvest.get_total_distribution()
               }

                events.append(event)
                del event

        return JsonResponse(events, safe=False)


def handler400(request, exception):
    return render(request,'app/errors/400.html')

def handler403(request, exception):
    return render(request,'app/errors/403.html')

def handler404(request, exception):
    return render(request,'app/errors/404.html')

def handler500(request):
    return render(request,'app/errors/500.html')

def handler403_csrf_failue(request, reason=""):
    return render(request,'app/errors/403_csrf.html')

saskatoon/sitebase/templates/app/base/header.html
{% load static %}
{% load i18n %}

<div class="header-top-area">
    <div class="container">
        <div class="row">
            <div class="col-md-1 col-md-offset-0 col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3">
                <div class="logo-area">
                    <a href="/"><img src="{% static 'img/logo.png' %}" alt="Les Fruits Defendus - Saskatoon" /></a>
                </div>
            </div>
            <div class="col-md-5 col-xs-12">
                <div class="logo-area">
                    <h2 style="color:white">Les Fruits Défendus</h2>
                    <p style="color:white"><i>{% translate 'Collectif montréalais de cueillette urbaine de fruits' %}</i></p>
                </div>
            </div>
            <div class="col-md-6 col-xs-12">
                <div class="header-top-menu">
                    <ul class="nav navbar-nav notika-top-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <span class="menu-it-icon-pro">
                                        <span class="h5">{{ user }}</span>
                                    <i class="notika-icon notika-support"></i>
                                    </span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/admin/password_change/">{% translate "Change password" %}</a></li>
                                    <li><a href={% url "logout" %}>{% translate "Logout" %}</a></li>
                                </ul>
                            </li>
                            {% if user.is_staff %}
                                <li class="nav-item dropdown">
                                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                        <span><i class="notika-icon notika-app"></i></span></a>
                                    </a>
                                    <ul class="dropdown-menu">
                                        {% if perms.member.add_authuser %}
                                            <li> <a href="/person/create/">
                                                {% translate "Add user" %}</a></li>
                                        {% endif %}
                                        {% if perms.member.change_authuser %}
                                            <li><a href="/admin/member/authuser/">
                                                {% translate "Manage user" %}</a></li>
                                        {% endif %}
                                        {% if perms.member.change_organization %}
                                            <li><a href="/admin/member/organization/">
                                                {% translate "Manage beneficiary" %}</a></li>
                                        {% endif %}
                                        <li><a href="/admin/">{% translate "Admin panel" %}</a></li>
                                        <li><a href="/rosetta/">{% translate "Manage translations" %}</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        {% else %}
                            <li>
                                <a href='/login'>
                                    <span class="menu-it-icon-pro">
                                        <span class="h5">{% translate 'login' %}</span>
                                        <i class="notika-icon notika-support"></i>
                                    </span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="#" data-toggle="dropdown" role="button"
                               aria-expanded="false" class="nav-link dropdown-toggle">
                                <span class="menu-it-icon-pro h5">
                                    <span class="language-title">
                                        {% translate "Languague" %}:</span>
                                        {{ LANGUAGE_CODE }}
                                    <i class="fa fa-caret-down"></i>
                                </span>
                                <form action="{% url 'set_language' %}" method="post"
                                      style="display: none" id="change_language_form">
                                    {% csrf_token %}
                                    <input type="hidden" value="" name="language" id="language" />
                                </form>
                            </a>
                            <ul class="dropdown-menu">
                                {% for language in languages %}
                                <li><a lang_code="{{ language.code }}" class="change_language">
                                    {{ language.name_local|title }} ({{ language.code }})
                                </a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

saskatoon/sitebase/templates/app/base/menu.html
{% load static %}
{% load i18n %}

<!-- MOBILE MENU-->
<div class="mobile-menu-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="mobile-menu">
                    <nav id="dropdown">
                        <ul class="mobile-menu-nav">
                            <li class="{% if request.resolver_match.url_name == 'calendar' %}active{% endif %}">
                                <a href="/calendar">{% translate "Calendar" %} </a>
                            </li>
                            <li class="{% if request.resolver_match.url_name == 'harvest-list' %}active{% endif %}">
                                <a href="/harvest">{% translate "Harvests" %} </a>
                            </li>
                            <li class="{% if request.resolver_match.url_name == 'property-list' %}active{% endif %}">
                                <a href="/property">{% translate "Properties" %}</a>
                            </li>
                            <li class="{% if request.resolver_match.url_name == 'beneficiary-list' %}active{% endif %}">
                                <a href="/beneficiary">{% translate "Beneficiaries" %}</a>
                            </li>
                            <li class="{% if request.resolver_match.url_name == 'community-list' %}active{% endif %}">
                                <a href="/community">{% translate "Community" %}</a>
                            </li>
                            <li class="{% if request.resolver_match.url_name == 'equipment-list' %}active{% endif %}">
                                <a href="/equipment">{% translate "Equipment" %}</a>
                            </li>
                            <!-- <li class="{% if request.resolver_match.url_name == 'statistics' %}active{% endif %}">
                                 <a href="/stats">{% translate "Statistics" %}</a>
                                 </li> -->
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- MAIN MENU-->
<div class="main-menu-area mg-tb-40">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <ul class="nav nav-tabs tab-nav-center notika-menu-wrap menu-it-icon-pro">
                    <li class="{% if request.resolver_match.url_name == 'calendar' %}active{% endif %}">
                        <a href="/calendar"><i class="fa fa-table"></i> {% translate "Calendar" %}</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'harvest-list' %}active{% endif %}">
                        <a href="/harvest"><i class="fa fa-shopping-basket"></i> {% translate "Harvests" %}</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'property-list' %}active{% endif %}">
                        <a href="/property"><i class="glyphicon glyphicon-tree-deciduous"></i> {% translate "Properties" %}</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'beneficiary-list' %}active{% endif %}">
                        <a href="/beneficiary"><i class="fa fa-gift"></i> {% translate "Beneficiaries" %}</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'community-list' %}active{% endif %}">
                        <a href="/community"><i class="fa fa-users"></i> {% translate "Community" %}</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'equipment-list' %}active{% endif %}">
                        <a href="/equipment"><i class="fa fa-scissors"></i> {% translate "Equipment" %}</a>
                    </li>
                    <!-- <li class="{% if request.resolver_match.url_name == 'statistics' %}active{% endif %}">
                         <a href="/stats"><i class="fa fa-bar-chart fa-fw"></i> {% translate "Statistics" %}</a>
                         </li> -->
                </ul>
            </div>
        </div>
    </div>
</div>

saskatoon/sitebase/templates/app/base/scripts.html
{% load static %}

<!-- bootstrap JS
    ============================================ -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- wow JS
    ============================================ -->
<script src="{% static 'js/wow.min.js' %}"></script>
<!-- price-slider JS
    ============================================ -->
<script src="{% static 'js/jquery-price-slider.js' %}"></script>
<!-- owl.carousel JS
    ============================================ -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- scrollUp JS
    ============================================ -->
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<!-- meanmenu JS
    ============================================ -->
<script src="{% static 'js/meanmenu/jquery.meanmenu.js' %}"></script>
<!-- counterup JS
    ============================================ -->
<script src="{% static 'js/counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/counterup/waypoints.min.js' %}"></script>
<script src="{% static 'js/counterup/counterup-active.js' %}"></script>
<!-- mCustomScrollbar JS
    ============================================ -->
<script src="{% static 'js/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<!-- jvectormap JS
    ============================================ -->
<script src="{% static 'js/jvectormap/jquery-jvectormap-2.0.2.min.js' %}"></script>
<script src="{% static 'js/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'js/jvectormap/jvectormap-active.js' %}"></script>
<!-- sparkline JS
    ============================================ -->
<script src="{% static 'js/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'js/sparkline/sparkline-active.js' %}"></script>
<!-- flot JS
    ============================================ -->
<script src="{% static 'js/flot/jquery.flot.js' %}"></script>
<script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'js/flot/curvedLines.js' %}"></script>
<script src="{% static 'js/flot/flot-active.js' %}"></script>
<!-- knob JS
    ============================================ -->
<script src="{% static 'js/knob/jquery.knob.js' %}"></script>
<script src="{% static 'js/knob/jquery.appear.js' %}"></script>
<script src="{% static 'js/knob/knob-active.js' %}"></script>
<!--  wave JS
    ============================================ -->
<script src="{% static 'js/wave/waves.min.js' %}"></script>
<script src="{% static 'js/wave/wave-active.js' %}"></script>
<!--  todo JS
    ============================================ -->
<script src="{% static 'js/todo/jquery.todo.js' %}"></script>
<!-- plugins JS
    ============================================ -->
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Data Table JS
            ============================================ -->
<script src="{% static 'js/data-table/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/data-table/data-table-act.js' %}"></script>
<!--  Chat JS
    ============================================ -->
<script src="{% static 'js/chat/moment.min.js' %}"></script>
<script src="{% static 'js/chat/jquery.chat.js' %}"></script>
<!-- main JS
    ============================================ -->
<script src="{% static 'js/main.js' %}"></script>
<!-- tawk chat JS
    ============================================ -->
<!-- <script src="{% static 'js/tawk-chat.js' %}"></script> -->
<!-- icheck JS
    ============================================ -->
<script src="{% static 'js/icheck/icheck.min.js' %}"></script>
<script src="{% static 'js/icheck/icheck-active.js' %}"></script>
<!-- Login JS
    ============================================ -->
<script src="{% static 'js/login/login-action.js' %}"></script>
<!-- bootstrap JS
    ============================================ -->
<script src="{% static 'js/django_select2/django_select2.js' %}"></script>
<!-- FullCalendar JS
============================================ -->
<script src="{% static 'js/moment/min/moment.min.js' %}"></script>
<script src="{% static 'js/fullcalendar/lib/main.min.js' %}"></script>
<!-- DatePicker JS
     ============================================ -->
<script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>

<!-- DateTime Pickers -->
<script>
 $(function () {
     $("#id_start_date").datetimepicker({
         format: 'd/m/Y H:i',
     });

     $("#id_end_date").datetimepicker({
         format: 'd/m/Y H:i',
     });

     $("#id_approximative_maturity_date").datetimepicker({
         format: 'Y-m-d',
     });
 });
</script>

<!-- Language selection -->
<script>
 $('.change_language').click(function(e){
     e.preventDefault();
     $('#language').val($(this).attr('lang_code'));
     $('#change_language_form').submit();
 });
</script>